[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]

[tool.setuptools.packages.find]
where = ["."]
include = ["coregix*"]

[tool.setuptools.package-data]
coregix = ["py.typed"]

[project]
name = "coregix"
version = "0.3.0"
description = "Pairwise raster coregistration for geospatial imagery"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Joseph Emile Honour Percival", email = "ipercival@gmail.com"},
    {name = "Kanoa Lindiwe", email = "cankanoa@gmail.com"}
]
maintainers = [
    {name = "Joseph Emile Honour Percival", email = "ipercival@gmail.com"}
]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "affine>=2.4",
    "numpy>=2.2",
    "rasterio>=1.4.3",
    "itk-elastix>=0.19.2"
]

[project.optional-dependencies]
docs = [
    "mkdocs>=1.6,<2",
    "mkdocs-material>=9.5",
    "mkdocstrings[python]>=0.26"
]
test = [
    "pytest>=7.4"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.urls]
"Source" = "https://github.com/iosefa/coregix"

[project.scripts]
align-image-pair = "coregix.cli.align_image_pair:main"
apply-coregix-transform = "coregix.cli.apply_coregix_transform:main"
evaluate-vector-alignment = "coregix.cli.evaluate_vector_alignment:main"
